VREP_PATH :=${HOME}/software/vrep
TARGET    :=Dummy

SOURCES   := DummyPlugin.cpp

INCLUDE   := ./include
SRC       := ./src
BUILD     := ./build
LIB       := ./lib

CXXFLAGS  := -Wall -O3
LDFLAGS   := -O1
INCLUDES  := ${INCLUDE}
LDPATHS   :=
LIBS      :=
SYMBOLS   :=

include ../make/plugin.mk
